{
 "title": "Cluster",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "leader_controller",
    "query": {
     "query": "label_values(vanus_controller_leader_flag{is_leader=\"true\"}, instance)"
    }
   },
   { "name": "mb", "query": "1048576" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Eventbus Number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vanus_controller_eventbus_number_total{instance=\"$leader_controller\"}"
    }
   ]
  },
  {
   "title": "Eventlog Number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vanus_controller_eventlog_number_total_per_eventbus{instance=\"$leader_controller\"})"
    }
   ]
  },
  {
   "title": "Event Number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vanus_controller_segment_event_number_total_per_eventlog{instance=\"$leader_controller\"})",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Data Size(MB)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vanus_controller_segment_size_total_per_eventlog{instance=\"$leader_controller\"}) / $mb",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Capacity Used(MB)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vanus_controller_segment_capacity_total_per_eventlog{instance=\"$leader_controller\"}) / $mb",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Working Segments",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(vanus_controller_segment_number_total_per_eventlog{instance=\"$leader_controller\", segment_state=\"working\"})",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Segment Provisioning",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "vanus_controller_segment_created_by_cache_missing_total{instance=\"$leader_controller\"}+vanus_controller_segment_created_by_scale_task_total{instance=\"$leader_controller\"}",
     "legendFormat": "Sum"
    },
    {
     "expr": "vanus_controller_segment_created_by_scale_task_total{instance=\"$leader_controller\"}",
     "legendFormat": "Auto Scale"
    },
    {
     "expr": "vanus_controller_segment_created_by_cache_missing_total{instance=\"$leader_controller\"}",
     "legendFormat": "Cache Missing"
    }
   ]
  },
  {
   "title": "Send Request(TPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(vanus_gateway_send_event_request_latency_summary_count[1m])",
     "legendFormat": "sum - {{instance}}"
    }
   ]
  },
  {
   "title": "Send Request(Latency)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 12 },
   "targets": [
    {
     "expr": "vanus_gateway_send_event_request_latency_summary",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true
  },
  {
   "title": "Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true
  },
  {
   "title": "Timer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true
  },
  {
   "title": "Trigger",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true
  }
 ]
}