{
 "title": "Go Runtime",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(go_goroutines, job)"
    }
   },
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "label_values(go_goroutines{job=\"$cluster\"}, container_name)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(go_goroutines{job=\"$cluster\", container_name=~\"$component\"}, pod_name)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_mspan_inuse_bytes - {{pod_name}}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_mspan_sys_bytes - {{pod_name}}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_mcache_inuse_bytes - {{pod_name}}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_mcache_sys_bytes - {{pod_name}}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_buck_hash_sys_bytes - {{pod_name}}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_gc_sys_bytes - {{pod_name}}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"} - go_memstats_other_sys_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_other_sys_bytes - {{pod_name}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_next_gc_bytes - {{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_heap_alloc_bytes - {{pod_name}}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_heap_sys_bytes - {{pod_name}}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_heap_idle_bytes - {{pod_name}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_heap_inuse_bytes - {{pod_name}}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_heap_released_bytes - {{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_stack_inuse_bytes - {{pod_name}}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_stack_sys_bytes - {{pod_name}}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_sys_bytes - {{pod_name}}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"} - go_memstats_frees_total{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_mallocs_total - {{pod_name}}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}[1m])",
     "legendFormat": "go_memstats_mallocs_total - {{pod_name}}"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}[1m])",
     "legendFormat": "go_memstats_lookups_total - {{pod_name}}"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}[1m])",
     "legendFormat": "go_memstats_alloc_bytes_total - {{pod_name}}"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_goroutines - {{pod_name}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_gc_duration_seconds - {{pod_name}}"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "process_resident_memory_bytes - {{pod_name}}"
    },
    {
     "expr": "process_virtual_memory_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "process_virtual_memory_bytes - {{pod_name}}"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "process_resident_memory_bytes - {{pod_name}}"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "process_virtual_memory_bytes - {{pod_name}}"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_alloc_bytes - {{pod_name}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}[30s])",
     "legendFormat": "go_memstats_alloc_bytes_total - {{pod_name}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_stack_inuse_bytes - {{pod_name}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_heap_inuse_bytes - {{pod_name}}"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "go_memstats_alloc_bytes - {{pod_name}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "go_memstats_alloc_bytes_total - {{pod_name}}"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "go_memstats_stack_inuse_bytes - {{pod_name}}"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "go_memstats_heap_inuse_bytes - {{pod_name}}"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "process_open_fds - {{pod_name}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "process_open_fds - {{pod_name}}"
    }
   ]
  }
 ]
}