{
 "title": "Pod - Go Processes",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(go_goroutines, job)"
    }
   },
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "label_values(go_goroutines{job=\"$cluster\"}, container_name)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(go_goroutines{job=\"$cluster\", container_name=~\"$component\"}, pod_name)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "process_resident_memory_bytes - {{pod_name}}"
    },
    {
     "expr": "process_virtual_memory_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "process_virtual_memory_bytes - {{pod_name}}"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "process_resident_memory_bytes - {{pod_name}}"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "process_virtual_memory_bytes - {{pod_name}}"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_alloc_bytes - {{pod_name}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}[30s])",
     "legendFormat": "go_memstats_alloc_bytes_total - {{pod_name}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_stack_inuse_bytes - {{pod_name}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_memstats_heap_inuse_bytes - {{pod_name}}"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "go_memstats_alloc_bytes - {{pod_name}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "go_memstats_alloc_bytes_total - {{pod_name}}"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "go_memstats_stack_inuse_bytes - {{pod_name}}"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "go_memstats_heap_inuse_bytes - {{pod_name}}"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "process_open_fds - {{pod_name}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}[$interval])",
     "legendFormat": "process_open_fds - {{pod_name}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_goroutines - {{pod_name}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"^($cluster)$\",container_name=~\"^($component)$\",pod_name=~\"^($pod)$\"}",
     "legendFormat": "go_gc_duration_seconds - {{pod_name}}"
    }
   ]
  }
 ]
}