{
 "title": "Summary",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Eventbus Number",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vanus_controller_eventbus_number_total{job=\"vanus\"}"
    }
   ]
  },
  {
   "title": "Eventlog Number",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vanus_controller_eventlog_number_total"
    }
   ]
  },
  {
   "title": "Active Segment Number",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(vanus_controller_segment_number_per_eventbus_total)"
    }
   ]
  },
  {
   "title": "segment_creation_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "vanus_controller_segment_creation_runtime"
    }
   ]
  },
  {
   "title": "segment_deleted_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "vanus_controller_deleted_segment_number_runtime"
    }
   ]
  },
  {
   "title": "Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true
  },
  {
   "title": "Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true
  },
  {
   "title": "Timer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true
  },
  {
   "title": "Trigger",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true
  }
 ]
}